name: Unit Tests & Build

on:
  pull_request:

concurrency:
  group: tests-build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - run: npm ci
      - run: npm run typecheck
      - run: npm run test
      - run: npx ng build
